//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GoldMS2RDMSExceptRpt.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "12.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Q")]
        public string sharePointDrive {
            get {
                return ((string)(this["sharePointDrive"]));
            }
            set {
                this["sharePointDrive"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"<?xml version=""1.0"" encoding=""utf-16""?>
<ArrayOfString xmlns:xsi=""http://www.w3.org/2001/XMLSchema-instance"" xmlns:xsd=""http://www.w3.org/2001/XMLSchema"">
  <string>stephen.m.su@boeing.com</string>
  <string>dawn.m.stevens@boeing.com</string>
  <string>lawrence.d.sims@boeing.com</string>
</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection sendTo {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["sendTo"]));
            }
            set {
                this["sendTo"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"<?xml version=""1.0"" encoding=""utf-16""?>
<ArrayOfString xmlns:xsi=""http://www.w3.org/2001/XMLSchema-instance"" xmlns:xsd=""http://www.w3.org/2001/XMLSchema"">
  <string>arturo.c.valle@boeing.com</string>
  <string>steven.d.larsen@boeing.com</string>
  <string>rick.e.phillips@boeing.com</string>
  <string>brad.s.behrens@boeing.com</string>
  <string>viji.menon@boeing.com</string>
  <string>michael.j.brady6@boeing.com</string>
  <string>douglas.s.elder@boeing.com</string>
  <string>paul.r.petrucelly@boeing.com</string>
</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection sendCC {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["sendCC"]));
            }
            set {
                this["sendCC"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("system_compare.xls")]
        public string exceptRpt {
            get {
                return ((string)(this["exceptRpt"]));
            }
            set {
                this["exceptRpt"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("\\\\vtr2b.web.boeing.com\\ids\\escmtools\\Team Documents")]
        public string sharePointUNC {
            get {
                return ((string)(this["sharePointUNC"]));
            }
            set {
                this["sharePointUNC"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool displayGrid {
            get {
                return ((bool)(this["displayGrid"]));
            }
            set {
                this["displayGrid"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool showMsgBox {
            get {
                return ((bool)(this["showMsgBox"]));
            }
            set {
                this["showMsgBox"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Monday")]
        public global::System.DayOfWeek runDay {
            get {
                return ((global::System.DayOfWeek)(this["runDay"]));
            }
            set {
                this["runDay"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("7")]
        public int startTime {
            get {
                return ((int)(this["startTime"]));
            }
            set {
                this["startTime"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("12")]
        public int endTime {
            get {
                return ((int)(this["endTime"]));
            }
            set {
                this["endTime"] = value;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("GOLD MS2 RDMS Exception Report")]
        public string appName {
            get {
                return ((string)(this["appName"]));
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("GoldMS2RDMSExceptRpt.htm")]
        public string emailMsg {
            get {
                return ((string)(this["emailMsg"]));
            }
            set {
                this["emailMsg"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool confirmDuplicate {
            get {
                return ((bool)(this["confirmDuplicate"]));
            }
            set {
                this["confirmDuplicate"] = value;
            }
        }
    }
}
